# Site settings
exclude: [README.md]
title: Lena Voita
email: lena-voita@yandex-team.ru
github: lena-voita
scholar_id: EcN9o7kAAAAJ
description: > # this symbol means ignore newlines until "baseurl:"
    Here you will find details about my work.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://lena-voita.github.io" # the base hostname & protocol for your site
#paginate: 3

# you can also declare arbitrary key-value data here
my_variable_name: my_value


# Build settings
markdown: kramdown
